<a href="https://colab.research.google.com/github/ShivinM-17/Tensorflow_practises/blob/main/tensorflow_nb_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamental of Tensorflow

#### Importing the module

In [ ]:
# Importing the tensorflow module
import tensorflow as tf
print(tf.__version__)

2.12.0


### Creating tensors using tf.constant()

In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the number of dimensions of a tensor
scalar.ndim         # ndim -> number of dimensions

0

Gives 0 as output since we have a constant in the tensor, which does not have any dimension

In [ ]:
# Create a vector
vector = tf.constant([10,10,10])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [ ]:
# Now, checking the dimension of the vector
vector.ndim

1

Gives 1 as output, since now, we have a list of tensors, thus having dimensions as 1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7,1],
                      [7,10,1]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  1],
       [ 7, 10,  1]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Creating another matric
mat = tf.constant([[10.,7.],
                   [3.,2.],
                   [8.,9.]],
                   dtype=tf.float16     # Giving the elements as float16 datatype
                  )

In [ ]:
mat

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Number of dimensions of mat
mat.ndim

2

In [ ]:
# Creating another tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]],
                      ])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Here, we see that there are 3 rows of data in the tensor variable, thus giving it dimension as 3

Thus, we have -                           
1) Scalar - a single number               
2) Vector - a number with direction       
3) Matrix - a 2D array of numbers          
4) Tensors - a n-dimensional array of numbers, where n being any number

### Creating tensors using tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [ ]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# Changing elements in changable tensor
changeable_tensor[0]=7      # This will give a error
changeable_tensor

In [ ]:
# Using assign function
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

We are able to change the elements in the tensor made using Variable()

In [ ]:
# Trying to change in the unchangeable_tensor
unchangeable_tensor[0].assign(7)   # This gives an error

Thus, tensors made using tf.constant() are not changeable

### Creating tensors using random tensors

Tensors of arbitrary size made of random numbers

In [ ]:
random_1 = tf.random.Generator.from_seed(20)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.88051325, -1.6833194 ],
       [ 0.86754173, -0.19625713],
       [-1.322665  , -0.02279496]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

Random seed generator helps to generate numbers, whose values may resolve around the inputted seed number.

Using normal function, we get random numbers from a normal distribution

### Shuffling the order of the elements in a tensor

In [ ]:
# Shuffling a tensor
# Valueable when shuffling of data is wanted, in such a way that inherent ordering of data doesn't affect the learning of the tensors

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=-41)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)    # Global level random seed
tf.random.shuffle(not_shuffled, seed=42)    # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

For our tensors to be in same tensor, we must use global level random seeds to do so

### Creating tensors using NumPy Arrays

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Turning Numpy arrays into tensors
import numpy as np

# Creating a numpy aray between 1 and 25
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2*3*4

24

In [ ]:
A.ndim, B.ndim

(3, 1)

### Getting information out of tensors

Shape, Rank, Axis or Dimension, Size

In [ ]:
# Creating a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[1][1][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ",rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Shape of elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Shape of elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Shape of elements along the 0 axis:  2
Shape of elements along the last axis:  5
Total number of elements in the tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in the tensor:  120


### Indexing the tensors

Tensors are indexed just like normal python lists

In [ ]:
# Given the tensor
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Getting first 2 elements of each dimension of the tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get first element from each dimension from each index, except for final one
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:2,:4,:2,:3]


<tf.Tensor: shape=(2, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Creating a rank 2 tensor
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Getting last item of each of our rank 2 tensor
rank_2_tensor[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [ ]:
# Adding extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[:, tf.newaxis]

In [ ]:
rank_3_tensor

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[... , tf.newaxis]

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

Basic Operations ( + , - , * , / )

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Note that these operations do not affect the original tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor-100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-90, -93],
       [-97, -96]], dtype=int32)>

In [ ]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# Using built-in tensorflow functions
tf.math.multiply(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
tf.add(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

### Matrix Multiplication

In ML, matrix multiplication of tensors is common operations

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Tensors with different shapes
s1_tensor = tf.constant([[1,2,5],
                         [7,2,1],
                         [3,3,3]])

s2_tensor = tf.constant([[3,5],
                         [6,7],
                         [1,8]])
s1_tensor, s2_tensor

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
s1_tensor @ s2_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
tf.matmul(s1_tensor,s2_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Reshaping matrices to multiply them
# Here, s2_tensor has shape as (3,2)
# Reshaping it as (2,3) helps to mulitply it with itself
tf.matmul(s2_tensor,tf.reshape(s2_tensor,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [ ]:
# Now, checking with transpose matrix
X = s2_tensor

In [ ]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [ ]:
# Checking differences between multiplication with transpose matrix, and matrix with replacement
tf.matmul(X, tf.transpose(X))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

In [ ]:
tf.matmul(s2_tensor,tf.reshape(s2_tensor,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

#### Dot product

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.tensordot(tensor,tensor,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Changing datatype of the tensor

In [ ]:
# Creating a new tensor
A = tf.constant([12,14.])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 14.], dtype=float32)>

In [ ]:
A.dtype

tf.float32

In [ ]:
# Change from float32 to float16 (reduced Precision)
B = tf.cast(A, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([12., 14.], dtype=float16)>

In [ ]:
# Change from int32 to float32
C = tf.constant([1,2])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
D = tf.cast(C, dtype = tf.float32)
D

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
# Change from int32 to float16
E = tf.cast(C, dtype = tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

### Aggregating tensors (min, max, mean, etc.)

In [ ]:
# Creating a tensor
T = tf.constant([[-2,5],[-1,-7]])
T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2,  5],
       [-1, -7]], dtype=int32)>

In [ ]:
# Getting the absolute values
tf.abs(T)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 5],
       [1, 7]], dtype=int32)>

In [ ]:
# Creating a random tensor
F = tf.constant(np.random.randint(0,100,size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 57, 18, 77,  8, 32, 92, 33, 19,  5, 77, 80, 15, 27, 92, 47,  4,
       71, 39, 78, 14, 37, 82, 26, 53, 34,  7, 41, 98, 16, 90,  7, 56, 23,
       19, 76, 81,  3, 76, 63, 39, 59, 13, 11,  9, 94, 91, 56, 18,  2])>

In [ ]:
F.shape, F.ndim, tf.size(F)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [ ]:
# Find the minimum
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Find the maximum
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [ ]:
# Find the sum
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2243>

In [ ]:
# Finding the variance
# NOTE - make sure that the tensor is either real or complex (i.e. float)
G = tf.cast(F, dtype = tf.float32)
tf.math.reduce_variance(G)

<tf.Tensor: shape=(), dtype=float32, numpy=947.0003>

In [ ]:
# Alternative way of getting variance
import tensorflow_probability as tfp
tfp.stats.variance(G)

<tf.Tensor: shape=(), dtype=float32, numpy=947.0003>

In [ ]:
# Finding the square root of each element of the tensor
tf.sqrt(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([8.83176  , 7.5498343, 4.2426405, 8.774964 , 2.828427 , 5.656854 ,
       9.591663 , 5.7445626, 4.358899 , 2.236068 , 8.774964 , 8.944272 ,
       3.8729835, 5.196152 , 9.591663 , 6.8556547, 2.       , 8.426149 ,
       6.244998 , 8.83176  , 3.7416575, 6.0827627, 9.055386 , 5.0990195,
       7.28011  , 5.8309517, 2.6457512, 6.4031243, 9.899495 , 4.       ,
       9.486833 , 2.6457512, 7.483315 , 4.7958317, 4.358899 , 8.717798 ,
       9.       , 1.7320508, 8.717798 , 7.937254 , 6.244998 , 7.6811457,
       3.6055512, 3.3166249, 3.       , 9.69536  , 9.539392 , 7.483315 ,
       4.2426405, 1.4142135], dtype=float32)>

In [ ]:
# Finding the standard deviation
tf.math.reduce_std(G)

<tf.Tensor: shape=(), dtype=float32, numpy=30.77337>

### Positional maximum and minimum of a tensor

In [ ]:
# Create a new tensor for finding positional maximum and minimum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

#### Positional maximum

In [ ]:
# Finding positional maximum
tf.argmax(F)       # this gives the index of the position of maximum element
# Here, maximum value is at position 42

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Get the maximum element
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

#### Positional Minimum

In [ ]:
# Finding the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (Removing all 1D axes)

In [ ]:
# Creating a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,2,1,1,25))
G

<tf.Tensor: shape=(1, 2, 1, 1, 25), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]]],


        [[[0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 2, 1, 1, 25])

In [ ]:
tf.squeeze(G)

<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
       [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
      dtype=float32)>

In [ ]:
tf.squeeze(G).shape

TensorShape([2, 25])

### One-Hot Encoding of tensors

In [ ]:
# Create a list of indices
l = [0,1,2,3,1]
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]], dtype=float32)>

In [ ]:
l = [[0,1,2,3,1],[2,3,0,1,3]]
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(2, 5, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]]], dtype=float32)>

### Some more math operations

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Finding square of all elements in the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Finding the square root of all elements in the tensor
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Finding the log of all elements in the tensor
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
tf.cast(H,dtype=tf.complex64)

<tf.Tensor: shape=(9,), dtype=complex64, numpy=
array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j], dtype=complex64)>

### Tensors and NumPy

In [ ]:
# Creating a tensor using a numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#  Convert tensor J to Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

In [ ]:
numpy_J, tensor_J

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

The tensor made with the numpy array is of **float64**, while the one made with only a list, it is of **float32** datatype

### Tensorflow tensor can run on GPU/TPU for faster numerical computations

In [ ]:
# Accessing the devices we are using in this colab notebook
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

Right now, we can see that we are only using the CPU

In [ ]:
!nvidia-smi

Fri Jun 23 16:37:43 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------